"""
Author: Put your name here
"""

PC_1 = [
    [57, 49, 41, 33, 25, 17, 9, 1],
    [58, 50, 42, 34, 26, 18, 10, 2],
    [59, 51, 43, 35, 27, 19, 11, 3],
    [60, 52, 44, 36, 63, 55, 47, 39],
    [31, 23, 15, 7, 62, 54, 46, 38],
    [30, 22, 14, 6, 61, 53, 45, 37],
    [29, 21, 13, 5, 28, 20, 12, 4],
]

PC_2 = [
    [14, 17, 11, 24, 1, 5, 3, 28],
    [15, 6, 21, 10, 23, 19, 12, 4],
    [26, 8, 16, 7, 27, 20, 13, 2],
    [41, 52, 31, 37, 47, 55, 30, 40],
    [51, 45, 33, 48, 44, 49, 39, 56],
    [34, 53, 46, 42, 50, 36, 29, 32],
]


def pc_1(key):
    """
    Permuted Choice - 1
    :param key: 64-bit initial key
    :return: 56-bit string to be fed to 16 rounds of transformation
    """
    output = ""

    for row in range(7):
        for col in range(8):
            index = PC_1[row][col] - 1
            output += key[index]

    return output


def pc_2(input):
    """
    Permuted Choice - 2
    :param inputString: 56-bit string generated by a transform
    :return: 48-bit subkey
    """
    output = ""

    for row in range(6):
        for col in range(8):
            index = PC_2[row][col] - 1
            output += input[index]

    return output


def shift_left(half, offset):
    """
    :param half: a string of 28-bits
    :param offset: 1 or 2 positions to be shifted
    :return: shifted half by offset positions
    """
    assert len(half) == 28
    return half[offset:] + half[:offset]


def shift_right(half, offset):
    assert len(half) == 28
    return half[28 - offset :] + half[: 28 - offset]


def generate_subkeys_encryption(key):
    """
    The key schedule for encryption generates 16 subkeys from main key
    :param key: main key of 64 bits
    :return: an array of 16 subkeys
    """
    subkeys = [""] * 16
    output = pc_1(key)
    c = output[:28]
    d = output[28:]

    for round in range(1, 17):
        if round in [1, 2, 9, 16]:
            c = shift_left(c, 1)
            d = shift_left(d, 1)
        else:
            c = shift_left(c, 2)
            d = shift_left(d, 2)
        subkeys[round - 1] = pc_2(c + d)

    return subkeys


def generate_subkeys_decryption(key):
    subkeys = [""] * 16
    output = pc_1(key)
    c = output[:28]
    d = output[28:]
    for round in range(1, 16 + 1):
        if round == 1:
            # don't shift
            pass
        elif round in [2, 9, 16]:
            # right shift by 1 bit
            c = shift_right(c, 1)
            d = shift_right(d, 1)
        else:
            # right shift by 2 bits
            c = shift_right(c, 2)
            d = shift_right(d, 2)
        # combine c and d, then do a PC-2 substitution
        subkeys[round - 1] = pc_2(c + d)
    return subkeys
